title: 'Titanium Network 2.0'
tagline: 'With TitaniumNetwork's services, you can browse the internet freely without restriction and you do not have to worry about your school/work/company being able to see your activities!'
author:
  name: 'Joseph Kalter'

menu:
# Uncomment to activate the menu looping function in the header.html file under _includes
#- {name: 'About', url: 'about.html'}

social:
# Uncomment to activate the social media icon looping function in the footer.html file under _includes
#- {icon: 'github', link: 'https://www.github.com/lenpaul'}
